### ISSUE TITLE
Issue with running AnnotationBustR: Error in seqinr::query(paste0("AC=", new.access)) :    invalid request:"unknown accession number at (^): \"AC

### ISSUE THREAD

**Issue by bjkramerumnedu** [sborstein/AnnotationBustR#21]
Hello,

I'm trying to extract target genes that will generally be found in bacteria and cyanobacteria. Based on the tutorial I think I can still do this despite the "terms" for AnnotationBustR only being for mitochondria, chloroplast, etc.

I performed a novel search with the other packages (ape, seqinr, reutils) in NCBI to gather the accession numbers of nucleotide sequences that included the terms "bicA" and "bicarbonate" in all fields, and came back with ~3507 results:

bicA.search <- esearch(term = "bicA[All Fields] AND bicarbonate[All Fields] ", db = 'nuccore', usehistory = TRUE)#search

Because of the size of the search results, I had to export the accession files as a .txt file:

bicA.accessions<-efetch(bicA.search, rettype = "acc",retmode = "text", outfile = "~/Dropbox/UMD CIGLR PostDoc Information/CCM and Toxin Gene Data NCBI/New CCM gene search/bicA/bicA_ACC.txt")#fetch accessions

and reimport into R:

accessions.long.table <- read.table("~/Dropbox/UMD CIGLR PostDoc Information/CCM and Toxin Gene Data NCBI/New CCM gene search/bicA/bicA_ACC.txt",header = FALSE,stringsAsFactors = FALSE) 
accessions.long.accessions <- accessions.long.table$V1

I then created a data frame for the Locus, Type, and Name of the gene I'm looking for and applied mtDNAterms to the columns:

add.name<-data.frame("bicA","CDS", "bicA", stringsAsFactors = FALSE)
colnames(add.name)<-colnames(mtDNAterms)#make the columnames for this synonym those needed for AnnotationBustR

I then ran the following code to extract the sequences:

my.seqs<-AnnotationBust(Accessions=accessions.long.table$V1, Terms=add.name, Prefix="bicA", TidyAccessions=FALSE)

And proceeded to get the following error when the code starting looking in the files of certain taxa:

[1] "Working On Accession CAOKNM010000002 uncultured_Sulfurimonas_sp."

Error in seqinr::query(paste0("AC=", new.access)) : 
  invalid request:"unknown accession number at (^): \"AC

Any Idea what this means? Any help would be greatly appreciated thank you.

**Comment by sborstein** [comment]
Hi,

Thanks for using AnnotationBustR. Unfortunately, you will not be able to extract data for that accession with AnnotationBustR. AnnotationBustR uses seqinr to provide access to ACNUC for which it retrieves subsequences. Currently, the GenBank release used by seqinr to access ACNUC is 246, which was released in October 2021, so the latest sequences (yours is from February of 2023) are not accessible. Because it is not in the database is why it is throwing the `"unknown accession number at (^): "AC`

This, along with connectivity issues myself other users have had with seqinr ACNUC is why I am looking at alternative dependencies for up to date access of sequences as well as better stability. While I have pieces of this in place, I can't provide a timeline for when a new version may be available as I unfortunately have limited time to work on this during my current postdoc.

I'm going close this issue as it is not something I can address as it requires the seqinr/ACNUC team to provide access to the latest GenBank releases.

Thanks,
-Sam
